### ISSUE TITLE
Some pinned packages are downgrades, requiring an explicit `apt-get` flag

### ISSUE THREAD

**Issue by gkelly** [distrust-foundation/airgap#1]
At https://github.com/distrust-foundation/airgap/commit/310189ca84d479b1ae0cb0044bdb700bfc35020a, running `make` yields:

```
The following packages will be DOWNGRADED:
  ca-certificates libssl1.1 openssl
0 upgraded, 276 newly installed, 3 downgraded, 0 to remove and 16 not upgraded.
E: Packages were downgraded and -y was used without --allow-downgrades.
apt install failed. Likely throttled. Retrying in 10 mins...
```

The `apt-install` script runs `apt-get install -y apt-transport-https ca-certificates`, which results in a few packages getting pulled as dependencies. Those packages are then downgraded to the [package pins](https://github.com/distrust-foundation/airgap/blob/master/config/container/packages.list).

The versions of a few packages in apt have moved ahead of what is pinned. This now requires allowing downgrading when installing the pinned packages.

**Comment by lrvick** [comment]
Another user ran into this bug today.

Was happy to learn you already had filed a bug, and a fix, which appears exactly the right call to be able to get deterministic releases against older pins.

Thanks!

**Comment by gkelly** [comment]
I'm glad this approach is acceptable. Thank you for the review and merge!
